### ISSUE TITLE
rxjs 6.x / Angular 6.x issues

### ISSUE THREAD

**Issue by egandro** [Jovalent/ngx-zone-scheduler#1]
Hey!

There are issues with Angular 6.x

AsyncAction && AsyncScheduler is gone - this needs refactoring.

import { AsyncAction } from 'rxjs/scheduler/AsyncAction';
import { AsyncScheduler } from 'rxjs/scheduler/AsyncScheduler'; 
export declare class ZoneScheduler extends AsyncScheduler {
// ..

}

**Comment by errorx666** [comment]
Wow, I thought I was the only one using this lib.

Funny, I was just starting to figure out how to fix this, this morning.

Unfortunately, AsyncAction and AsyncScheduler have moved into the "internal" section of rxjs, so I can't just extend them.  I have to implement `SchedulerLike`, which is a pain, and I can't find good docs around it.

**Comment by errorx666** [comment]
PRs welcome though.

**Comment by egandro** [comment]
I copied it in my own project.

This is the fix:

import { AsyncAction } from 'rxjs/internal/scheduler/AsyncAction';
import { AsyncScheduler } from 'rxjs/internal/scheduler/AsyncScheduler';

**Comment by egandro** [comment]
yes make it the right way :))) for now it (semi)works for me

**Comment by errorx666** [comment]
Please try version 2.0.0 on npm.  Take note of the changes in the README.

**Comment by egandro** [comment]
Thx. That compiles.
